apiVersion: batch/v1
kind: Job
metadata:
  name: guestbook-ui
spec:
  template:
    spec:
      containers:
      - name: guestbook-ui
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4